TRAIN:
  DATASET: 'impact'
  EVAL_SPLIT: 'val'
  BATCH_SIZE: 1
  EVAL_BATCH_SIZE: 1
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: False
  EVAL_IGNORE_LABELS: []
DATA:
  PATH_TO_DATA_DIR: dataset/ATR
  TASK_TYPE: 'atr'
  CV_SPLIT_NUM: 1
  SPLITS_DIR: 'splits_FAS_R'
  GROUND_TRUTH_DIR: 'groundTruth_ATR_R'
  MASK_DIR: 'mask_ATR_R'
  ATR_SEGMENTS_DIR: 'atr_segments_R'
  FEATURES_DIR: 'features'
  MAPPING_FILE: 'mapping_ATR.txt'
  FEATURE_TYPE: 'videomaev2'
  SKIP_MISSING_FEATURES: True
  BACKGROUND_INDICES: []
  FRAME_SAMPLING_RATE: 1
MODEL:
  NAME: 'ltc'
  LOSS_FUNC: 'masked_bce'
  NUM_CLASSES: 6
  INPUT_DIM: 1408
SOLVER:
  BASE_LR: 0.00025
  MAX_EPOCH: 120
  WEIGHT_DECAY: 1e-3
  OPTIMIZING_METHOD: 'adam'
  LR_POLICY: 'constant_cosine_decay'
  WARMUP_EPOCHS: 15
  T_MAX: 120
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 115
LOG_PERIOD: 100
OUTPUT_DIR: ./experiments/impact_atr_r_videomaev2
TEST:
  ENABLE: False
  DATASET: 'impact'
  IGNORED_CLASSES: []
